### ISSUE TITLE
Allow for skipping of autogeneration of logging code

### ISSUE THREAD

**Issue by romeokienzler** [claimed-framework/c3#33]
We had a case where the autogenerated logging code breaks the underlying code (as a deepcopy would not allow for pickeling thread objects contained withing the logging framework)

I suggest a cli option like: --skip-logging

Current workaround: Using a custom Dockerfile and have that code removed:

RUN sed -i '3,35d' claimed_AGB_model_card_unfrozen_weights_Uper_321_br_env_vars.py

**Comment by blumenstiel** [comment]
@romeokienzler We do need to a short version of the setup code for the functionally (similar to the grid wrapper https://github.com/claimed-framework/c3/blob/main/src/c3/templates/gw_component_setup_code.py).
Would it work if we add this code instead of the longer version with logging when `--skip-logging` is used?

**Comment by romeokienzler** [comment]
Yes @blumenstiel I'd say so

**Comment by blumenstiel** [comment]
Added in #39
