### ISSUE TITLE
clean up generated files after successful run or before the next run

### ISSUE THREAD

**Issue by romeokienzler** [claimed-framework/c3#36]
current problem:

c3_create_gridwrapper s1download.ipynb -p "grid_process" -r us.icr.io/geodn creates gw_s1download.py and s1download.py - the latter causes the next run to fail with:

AssertionError: File s1download.py already exist. Cannot convert notebook.

**Comment by blumenstiel** [comment]
The file should be deleted after a successful run. 
Your sure that the previous run did not fail / that you don't have a local file with the same name?

**Comment by blumenstiel** [comment]
We might want to delete the temporary file after an unsuccessful run.

**Comment by romeokienzler** [comment]
yes, sorry, that's what I wanted to say, the compiler should cleanup all artifacts, ideally also when failing, but at least before the next start

**Comment by romeokienzler** [comment]
@blumenstiel

**Comment by romeokienzler** [comment]
![image](https://github.com/claimed-framework/c3/assets/5694071/69782b04-d39b-46cd-b68f-3b57c95bdb7b)

**Comment by blumenstiel** [comment]
@romeokienzler I removed these additional files in the current version.

The question is, if we also want to remove any files when running the grid wrapper. Currently, you can run the grid wrapper but not create an operator because you want to review the code first. Therefore, we should not delete the adjusted component file or the grid wrapper file. If we change the behavior such as create_gridwrapper always creates an operator, it would make more sense to clean up the generated files.

**Comment by romeokienzler** [comment]
Good point, I wasn't even aware that you can create a grid warpper without creating an operator.

What aboud adding a flag --keep-generated-code and also keep the Dockerfile? That one I was missing most.

If false (default) all generated assets are deleted on a successful run and tried to be deleted on failure and are deleted on a subsequent run before processing

**Comment by blumenstiel** [comment]
Added in #39
